---

- name: "1.3.1 | PATCH | Ensure AIDE is installed"
  block:
      - name: "1.3.1 | PATCH | Ensure AIDE is installed | Install"
        package:
            name: aide
            state: installed

      - name: "1.3.1 | PATCH | Ensure AIDE is installed | started"
        command: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
        changed_when: false
        failed_when: false
        async: 45
        poll: 0
        args:
            creates: /var/lib/aide/aide.db.gz
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - amznlnx2cis_config_aide
      - amznlnx2cis_rule_1_3_1
  tags:
      - level1
      - automated
      - patch
      - rule_1.3.1
      - aide

- name: "1.3.2 | PATCH | Ensure filesystem integrity is regularly checked"
  cron:
      name: Run AIDE integrity check
      minute: "{{ amznlnx2cis_aide_cron['aide_minute'] | default('0') }}"
      hour: "{{ amznlnx2cis_aide_cron['aide_hour'] | default('5') }}"
      day: "{{ amznlnx2cis_aide_cron['aide_day'] | default('*') }}"
      month: "{{ amznlnx2cis_aide_cron['aide_month'] | default('*') }}"
      weekday: "{{ amznlnx2cis_aide_cron['aide_weekday'] | default('*') }}"
      job: "{{ amznlnx2cis_aide_cron['aide_job'] }}"
  when:
      - amznlnx2cis_rule_1_3_2
  tags:
      - level1
      - automated
      - patch
      - rule_1.3.2
      - aide
      - file_integrity
